version: '2'
services:
  my-sql:
    image: mysql:8.0
    ports:
      - "4000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: nestdb
      MYSQL_DATABASE: nestdb
      MYSQL_USER: nestdb
      MYSQL_PASSWORD: nestdb
    volumes:
      - ./data/mysql:/var/lib/mysql
